--- 
- hosts: myhosts 
  become: yes 
  tasks: 
   - name: install java on ubuntu
     apt: 
       name: "{{myjavapackonubuntu}}"
       state: present 
     when: ansible_os_family=="Debian"

   - name: install java on Redhat 
     dnf:
       name: "{{myjavapackonubuntu}}"
       state: present 
     when: ansible_os_family=="Redhat" 
