--- 
- hosts: 172.31.39.142 
  become: yes 
  tasks: 
  - name: install git 
    apt: 
      name: git
      state: present 
    tags: mygit

  - name: install tree 
    apt: 
      name: tree 
      state: present 
    ignore_errors: true
    tags: mytree

  - name: install wget
    apt: 
      name: wget 
      state: present
    tags: mywget 