--- 
- hosts: 172.31.39.142 
  become: yes 
  tasks: 
  - include_tasks: myfile.yml
  - name: i want to copy a file into node side 
    copy: 
       src: mytestfile
       dest: /home/raju/mytestfile 
       
  - name: install apache2 
    apt:
       name: apache2 
       state: present 
  
  - name: copy myindex file into node side 
    template: 
      src: myindex.j2
      dest: /var/www/html/index.html

  - name: download internet file 
    get_url:
      url: https://github.com/aadya-31a/myansible-8-oct-2025/blob/main/group-vars/webserver
      dest: /home/raju/group-vars/webserver
      force_basic_auth: yes

    